package frost

import (
	"encoding/binary"
	"errors"
	"io"
	"math"

	"github.com/f3rmion/fy/group"
)

// SigningNonce holds the secret nonce values generated by a participant
// during round 1 of signing. These values must be kept secret and never reused.
type SigningNonce struct {
	// ID is the participant's identifier.
	ID group.Scalar

	// D is the hiding nonce (secret).
	D group.Scalar

	// E is the binding nonce (secret).
	E group.Scalar
}

// SigningCommitment is the public commitment broadcast by a participant
// during round 1 of signing.
type SigningCommitment struct {
	// ID is the participant's identifier.
	ID group.Scalar

	// HidingPoint is the public commitment to the hiding nonce (D * G).
	HidingPoint group.Point

	// BindingPoint is the public commitment to the binding nonce (E * G).
	BindingPoint group.Point
}

// SignatureShare is a participant's contribution to the final signature,
// produced during round 2 of signing.
type SignatureShare struct {
	// ID is the participant's identifier.
	ID group.Scalar

	// Z is the signature share value.
	Z group.Scalar
}

// validateCommitments checks that no commitment contains an identity point.
// Per RFC 9591 Section 4.3, identity commitment points must be rejected.
func validateCommitments(commitments []*SigningCommitment) error {
	for _, c := range commitments {
		if c.HidingPoint.IsIdentity() || c.BindingPoint.IsIdentity() {
			return errors.New("commitment contains identity point")
		}
	}
	return nil
}

// SignRound1 generates fresh nonces and a public commitment for a signing
// session. The returned [SigningNonce] must be kept secret and passed to
// [FROST.SignRound2]. The returned [SigningCommitment] must be broadcast
// to all other signers.
//
// Each call to SignRound1 generates new random nonces. Nonces must never
// be reused across signing sessions.
func (f *FROST) SignRound1(r io.Reader, share *KeyShare) (*SigningNonce, *SigningCommitment, error) {
	d, err := f.group.RandomScalar(r)
	if err != nil {
		return nil, nil, err
	}
	e, err := f.group.RandomScalar(r)
	if err != nil {
		return nil, nil, err
	}
	// Defense-in-depth: verify nonces are non-zero.
	// RandomScalar implementations should exclude zero, but a buggy implementation
	// could leak secret key information if zero nonces are used.
	if d.IsZero() || e.IsZero() {
		return nil, nil, errors.New("generated zero nonce (RandomScalar bug)")
	}

	nonce := &SigningNonce{
		ID: share.ID,
		D:  d,
		E:  e,
	}

	commitment := &SigningCommitment{
		ID:           share.ID,
		HidingPoint:  f.group.NewPoint().ScalarMult(d, f.group.Generator()),
		BindingPoint: f.group.NewPoint().ScalarMult(e, f.group.Generator()),
	}

	return nonce, commitment, nil
}

// SignRound2 computes this participant's signature share for the given message.
// It requires the participant's key share, their secret nonce from round 1,
// the message to sign, and all signing commitments from participating signers.
//
// The commitments slice must include commitments from all signers participating
// in this signing session (at least threshold signers).
func (f *FROST) SignRound2(
	share *KeyShare,
	nonce *SigningNonce,
	message []byte,
	commitments []*SigningCommitment,
) (*SignatureShare, error) {
	// Validate commitment list
	if len(commitments) == 0 {
		return nil, errors.New("empty commitment list")
	}
	if len(commitments) < f.threshold {
		return nil, errors.New("not enough commitments to meet threshold")
	}
	if err := validateCommitments(commitments); err != nil {
		return nil, err
	}

	// Check for consumed nonces
	if nonce.D == nil || nonce.D.IsZero() || nonce.E == nil || nonce.E.IsZero() {
		return nil, errors.New("nonce already consumed or invalid")
	}

	// Securely erase nonce scalars on exit to prevent memory residue.
	defer func() {
		nonce.D.Zero()
		nonce.E.Zero()
	}()

	// Check for duplicate signer IDs and verify own commitment is present
	seen := make(map[string]bool)
	ownFound := false
	for _, c := range commitments {
		key := string(c.ID.Bytes())
		if seen[key] {
			return nil, errors.New("duplicate signer ID in commitment list")
		}
		seen[key] = true
		if c.ID.Equal(share.ID) {
			ownFound = true
		}
	}
	if !ownFound {
		return nil, errors.New("own commitment not found in commitment list")
	}

	// Encode commitment list for binding factor computation
	encCommitList := f.encodeCommitments(commitments)

	// Compute binding factors for each signer using H1
	bindingFactors := f.computeBindingFactors(message, encCommitList, commitments)

	// Compute group commitment R = sum(D_i + rho_i * E_i)
	R := f.group.NewPoint()
	for _, comm := range commitments {
		rho := bindingFactors[string(comm.ID.Bytes())]
		rhoE := f.group.NewPoint().ScalarMult(rho, comm.BindingPoint)
		term := f.group.NewPoint().Add(comm.HidingPoint, rhoE)
		R = f.group.NewPoint().Add(R, term)
	}

	// Compute challenge c = H2(R, GroupKey, message)
	c := f.hasher.H2(f.group, R.Bytes(), share.GroupKey.Bytes(), message)

	// Compute Lagrange coefficient for this signer
	lambda, err := f.lagrangeCoefficient(share.ID, commitments)
	if err != nil {
		return nil, err
	}

	// Compute signature share: z_i = d + rho * e + lambda * s * c
	myRho := bindingFactors[string(share.ID.Bytes())]

	z := f.group.NewScalar().Mul(myRho, nonce.E)                // rho * e
	z = f.group.NewScalar().Add(nonce.D, z)                     // d + rho * e
	lambdaS := f.group.NewScalar().Mul(lambda, share.SecretKey) // lambda * s
	lambdaSC := f.group.NewScalar().Mul(lambdaS, c)             // lambda * s * c
	z = f.group.NewScalar().Add(z, lambdaSC)                    // d + rho*e + lambda*s*c

	return &SignatureShare{
		ID: share.ID,
		Z:  z,
	}, nil
}

// ComputeGroupCommitment computes the aggregate nonce commitment R from all
// signing commitments. This is useful for coordinators that need to compute
// the challenge externally (e.g., for circomlibjs compatibility).
//
// The computation is: R = Σ (D_i + ρ_i * E_i)
// where ρ_i = H1(i, msg, commitments) is the binding factor for participant i.
//
// The returned point R can be used to compute an external challenge:
//
//	c = poseidon([R.x, R.y, A.x, A.y, msg])
//
// This is particularly useful when signers (e.g., Ledger devices) need to
// receive a pre-computed challenge rather than computing it internally.
func (f *FROST) ComputeGroupCommitment(message []byte, commitments []*SigningCommitment) (group.Point, error) {
	if len(commitments) == 0 {
		return nil, ErrInvalidCommitment
	}
	if err := validateCommitments(commitments); err != nil {
		return nil, err
	}

	// Encode commitment list for binding factor computation
	encCommitList := f.encodeCommitments(commitments)

	// Compute binding factors for each signer using H1
	bindingFactors := f.computeBindingFactors(message, encCommitList, commitments)

	// Compute group commitment R = sum(D_i + rho_i * E_i)
	R := f.group.NewPoint()
	for _, comm := range commitments {
		rho := bindingFactors[string(comm.ID.Bytes())]
		rhoE := f.group.NewPoint().ScalarMult(rho, comm.BindingPoint)
		term := f.group.NewPoint().Add(comm.HidingPoint, rhoE)
		R = f.group.NewPoint().Add(R, term)
	}

	return R, nil
}

// AggregateWithVerification combines individual signature shares into a complete
// Schnorr signature, verifying each share before aggregation.
// This prevents a single malicious signer from producing an invalid signature.
//
// The publicKeys map must contain the public key for each signer, keyed by
// the string representation of their ID bytes.
func (f *FROST) AggregateWithVerification(
	message []byte,
	commitments []*SigningCommitment,
	shares []*SignatureShare,
	publicKeys map[string]group.Point,
	groupKey group.Point,
) (*Signature, error) {
	if len(shares) == 0 {
		return nil, errors.New("no signature shares provided")
	}
	if len(commitments) == 0 {
		return nil, errors.New("no commitments provided")
	}
	if len(shares) != len(commitments) {
		return nil, errors.New("shares and commitments count mismatch")
	}
	if err := validateCommitments(commitments); err != nil {
		return nil, err
	}

	// Verify each share before aggregation
	for _, share := range shares {
		pk, ok := publicKeys[string(share.ID.Bytes())]
		if !ok {
			return nil, errors.New("missing public key for signer")
		}
		valid, err := f.VerifyShare(share, pk, message, commitments, groupKey)
		if err != nil {
			return nil, err
		}
		if !valid {
			return nil, errors.New("invalid signature share detected")
		}
	}

	return f.Aggregate(message, commitments, shares)
}

// Aggregate combines individual signature shares into a complete Schnorr
// signature. The resulting signature can be verified using [FROST.Verify].
//
// All signature shares must be from the same signing session (same message
// and commitments).
func (f *FROST) Aggregate(
	message []byte,
	commitments []*SigningCommitment,
	shares []*SignatureShare,
) (*Signature, error) {
	if len(shares) == 0 {
		return nil, errors.New("no signature shares provided")
	}
	if len(commitments) == 0 {
		return nil, errors.New("no commitments provided")
	}
	if len(shares) != len(commitments) {
		return nil, errors.New("shares and commitments count mismatch")
	}
	if err := validateCommitments(commitments); err != nil {
		return nil, err
	}
	// Validate commitment IDs are unique, then match share IDs against them
	commitIDs := make(map[string]bool)
	for _, c := range commitments {
		key := string(c.ID.Bytes())
		if commitIDs[key] {
			return nil, errors.New("duplicate commitment ID in aggregation")
		}
		commitIDs[key] = true
	}
	shareIDs := make(map[string]bool)
	for _, s := range shares {
		key := string(s.ID.Bytes())
		if shareIDs[key] {
			return nil, errors.New("duplicate share ID in aggregation")
		}
		shareIDs[key] = true
		if !commitIDs[key] {
			return nil, errors.New("share ID does not match any commitment ID")
		}
	}

	// Encode commitment list and recompute R
	encCommitList := f.encodeCommitments(commitments)
	bindingFactors := f.computeBindingFactors(message, encCommitList, commitments)
	R := f.group.NewPoint()
	for _, comm := range commitments {
		rho := bindingFactors[string(comm.ID.Bytes())]
		rhoE := f.group.NewPoint().ScalarMult(rho, comm.BindingPoint)
		term := f.group.NewPoint().Add(comm.HidingPoint, rhoE)
		R = f.group.NewPoint().Add(R, term)
	}

	// Sum all z shares
	z := f.group.NewScalar()
	for _, s := range shares {
		z = f.group.NewScalar().Add(z, s.Z)
	}

	return &Signature{R: R, Z: z}, nil
}

// VerifyShare verifies an individual signature share against the signer's
// public key. This can be used by a coordinator to detect malicious signers
// before aggregation.
//
// The verification equation is: z_i * G == R_i + c * lambda_i * PK_i
// where R_i = D_i + rho_i * E_i is the signer's effective commitment.
func (f *FROST) VerifyShare(
	share *SignatureShare,
	publicKey group.Point,
	message []byte,
	commitments []*SigningCommitment,
	groupKey group.Point,
) (bool, error) {
	if err := validateCommitments(commitments); err != nil {
		return false, err
	}

	// Encode commitment list for binding factor computation
	encCommitList := f.encodeCommitments(commitments)
	bindingFactors := f.computeBindingFactors(message, encCommitList, commitments)

	// Compute group commitment R = sum(D_i + rho_i * E_i)
	R := f.group.NewPoint()
	var signerCommitment *SigningCommitment
	for _, comm := range commitments {
		rho := bindingFactors[string(comm.ID.Bytes())]
		rhoE := f.group.NewPoint().ScalarMult(rho, comm.BindingPoint)
		term := f.group.NewPoint().Add(comm.HidingPoint, rhoE)
		R = f.group.NewPoint().Add(R, term)
		if comm.ID.Equal(share.ID) {
			signerCommitment = comm
		}
	}

	if signerCommitment == nil {
		return false, errors.New("signer commitment not found")
	}

	// Compute challenge c = H2(R, GroupKey, message)
	c := f.hasher.H2(f.group, R.Bytes(), groupKey.Bytes(), message)

	// Compute Lagrange coefficient for this signer
	lambda, err := f.lagrangeCoefficient(share.ID, commitments)
	if err != nil {
		return false, err
	}

	// Compute R_i = D_i + rho_i * E_i
	rho := bindingFactors[string(share.ID.Bytes())]
	rhoE := f.group.NewPoint().ScalarMult(rho, signerCommitment.BindingPoint)
	Ri := f.group.NewPoint().Add(signerCommitment.HidingPoint, rhoE)

	// LHS: z_i * G
	lhs := f.group.NewPoint().ScalarMult(share.Z, f.group.Generator())

	// RHS: R_i + c * lambda_i * PK_i
	lambdaC := f.group.NewScalar().Mul(lambda, c)
	cLambdaPK := f.group.NewPoint().ScalarMult(lambdaC, publicKey)
	rhs := f.group.NewPoint().Add(Ri, cLambdaPK)

	return lhs.Equal(rhs), nil
}

// Verify checks whether a FROST signature is valid for the given message
// and group public key. Returns true if the signature is valid.
//
// This performs standard Schnorr signature verification:
// z*G == R + c*Y, where c = H2(R, Y, message).
func (f *FROST) Verify(message []byte, sig *Signature, groupKey group.Point) bool {
	if sig == nil || sig.R == nil || sig.Z == nil || groupKey == nil {
		return false
	}
	// Reject identity R per RFC 9591 Section 5.5
	if sig.R.IsIdentity() {
		return false
	}
	// c = H2(R, GroupKey, message)
	c := f.hasher.H2(f.group, sig.R.Bytes(), groupKey.Bytes(), message)

	// Check: z*G == R + c*Y
	lhs := f.group.NewPoint().ScalarMult(sig.Z, f.group.Generator())

	cY := f.group.NewPoint().ScalarMult(c, groupKey)
	rhs := f.group.NewPoint().Add(sig.R, cY)

	return lhs.Equal(rhs)
}

// encodeCommitments serializes the commitment list for hashing.
// The encoding is: 4-byte commitment count || for each commitment:
//
//	4-byte len || ID || 4-byte len || HidingPoint || 4-byte len || BindingPoint
//
// Length-prefixing prevents ambiguous concatenation boundaries (per FROST RFC).
func (f *FROST) encodeCommitments(commitments []*SigningCommitment) []byte {
	var commBytes []byte
	// Prepend commitment count per FROST RFC recommendation.
	var countBuf [4]byte
	binary.BigEndian.PutUint32(countBuf[:], uint32(len(commitments)))
	commBytes = append(commBytes, countBuf[:]...)
	for _, c := range commitments {
		commBytes = appendLengthPrefixed(commBytes, c.ID.Bytes())
		commBytes = appendLengthPrefixed(commBytes, c.HidingPoint.Bytes())
		commBytes = appendLengthPrefixed(commBytes, c.BindingPoint.Bytes())
	}
	return commBytes
}

// appendLengthPrefixed appends a 4-byte big-endian length prefix followed by data to dst.
func appendLengthPrefixed(dst, data []byte) []byte {
	if len(data) > math.MaxUint32 {
		panic("appendLengthPrefixed: data length exceeds uint32 max")
	}
	var lenBuf [4]byte
	binary.BigEndian.PutUint32(lenBuf[:], uint32(len(data)))
	dst = append(dst, lenBuf[:]...)
	dst = append(dst, data...)
	return dst
}

// computeBindingFactors derives the binding factor for each signer from
// the message and all signing commitments using H1. This ensures that each
// signer's contribution is bound to the specific signing session.
func (f *FROST) computeBindingFactors(message, encCommitList []byte, commitments []*SigningCommitment) map[string]group.Scalar {
	factors := make(map[string]group.Scalar)

	for _, c := range commitments {
		rho := f.hasher.H1(f.group, message, encCommitList, c.ID.Bytes())
		factors[string(c.ID.Bytes())] = rho
	}

	return factors
}

// lagrangeCoefficient computes the Lagrange interpolation coefficient for
// the given participant ID within the set of signing participants.
// This is used to combine signature shares into a valid threshold signature.
// Returns an error if the denominator is zero (e.g., duplicate signer IDs).
func (f *FROST) lagrangeCoefficient(id group.Scalar, commitments []*SigningCommitment) (group.Scalar, error) {
	num := f.scalarFromInt(1)
	den := f.scalarFromInt(1)

	for _, c := range commitments {
		if c.ID.Equal(id) {
			continue
		}
		// num *= c.ID
		num = f.group.NewScalar().Mul(num, c.ID)
		// den *= (c.ID - id)
		diff := f.group.NewScalar().Sub(c.ID, id)
		den = f.group.NewScalar().Mul(den, diff)
	}

	denInv, err := f.group.NewScalar().Invert(den)
	if err != nil {
		return nil, errors.New("lagrange coefficient: zero denominator (duplicate signer IDs?)")
	}
	return f.group.NewScalar().Mul(num, denInv), nil
}
